"""Generate lift.py."""
import pathlib

NL = chr(10)
LT = "<"
GT = ">"
BT = "`"

lines = []
a = lines.append

a('"""Self-verifying decompilation loop."""')
a('from __future__ import annotations')
a('import asyncio, os, re')
a('from dataclasses import dataclass, field')
a('from spectrida.verify.helpers import parse_struct_layout, find_external_calls, estimate_function_complexity')
a('from spectrida.verify.oracle import (EmulationResult, OracleVerdict, compile_c_to_shared, emulate_function, compare_emulations, extract_function_bytes)')
a('from spectrida.verify.capture_replay import capture_external_calls, replay_with_stubs, compare_with_replay')
a('from spectrida.verify.symbols import generate_symbol_stubs_from_pseudocode, load_symbol_database, generate_stubs_from_database')
a('NL = chr(10)')
a('')
a('@dataclass')
a('class LiftAttempt:')
a('    attempt_num: int = 0')
a('    c_code: str = ""')
a('    compiled: bool = False')
a('    compile_error: str = ""')
a('    verified: bool = False')
a('    verdict: OracleVerdict | None = None')
a('')
a('@dataclass')
a('class LiftResult:')
a('    func_name: str = ""')
a('    verified_c: str = ""')
a('    attempts: list = field(default_factory=list)')
a('    total_attempts: int = 0')
a('    success: bool = False')
a('')
a('def _extract_struct_context(pseudocode: str) -> str:')
a('    """Extract struct definitions from pseudocode."""')
a('    type_offsets = {}')
a('    for m in re.finditer(r\'\\*\\(\\((\\w+)\\s*\\*\\)\\s*\\((\\w+)\\s*\\+\\s*(\\d+)\\)\', pseudocode):')
a('        field_type = m.group(1)')
a('        offset = int(m.group(3))')
a('        if field_type not in type_offsets:')
a('            type_offsets[field_type] = []')
a('        type_offsets[field_type].append(offset)')
a('    structs = []')
a('    for field_type, offsets in type_offsets.items():')
a('        offsets.sort()')
a('        fields = [f"    {field_type} field_{o};" for o in offsets]')
a('        structs.append(f"typedef struct {{" + NL + NL.join(fields) + NL + "}} GameData;")')
a('    return NL.join(structs) if structs else ""')
a('')
a('def _normalize_types(code: str) -> str:')
a('    """Normalize C++ pseudocode for GCC C++ compilation."""')
a('    code = re.sub(r\'\\w+::\', \'\', code)')
a('    code = code.replace("this", "self")')
a('    code = re.sub(r\'\\(void\\* (\\w+)\\)\', r\'(ThisStruct* \\1)\', code)')
a('    replacements = [')
a('        ("__int64", "long long"), ("__int32", "int"), ("__int16", "short"),')
a('        ("__int8", "char"), ("_BYTE", "unsigned char"), ("_WORD", "unsigned short"),')
a('        ("_DWORD", "unsigned int"), ("_QWORD", "unsigned long long"),')
a('        ("__fastcall", ""), ("__cdecl", ""),')
a('        ("int64_t", "long long"), ("uint64_t", "unsigned long long"),')
a('        ("int32_t", "int"), ("uint32_t", "unsigned int"),')
a('        ("int16_t", "short"), ("uint16_t", "unsigned short"),')
a('        ("int8_t", "char"), ("uint8_t", "unsigned char"),')
a('        ("size_t", "unsigned long long"),')
a('    ]')
a('    for old, new in replacements:')
a('        code = code.replace(old, new)')
a('    known_types = {"int", "long", "char", "void", "float", "double", "unsigned",')
a('                   "signed", "short", "struct", "union", "enum", "const", "static",')
a('                   "extern", "volatile", "inline", "register", "auto", "typedef"}')
a('    def replace_unknown_type(m):')
a('        type_name = m.group(1)')
a('        if type_name.lower() in known_types or type_name.startswith("uint") or type_name.startswith("int"):')
a('            return m.group(0)')
a('        return f"ThisStruct* {m.group(2)}"')
a('    code = re.sub(r\'(\\w+)\\s*\\*\\s*(\\w+)\', replace_unknown_type, code)')
a('    code = re.sub(r\'&?off_[0-9a-fA-F]+\', "0", code)')
a('    code = re.sub(r\'&?unk_[0-9a-fA-F]+\', "0", code)')
a('    struct_def = "typedef struct { unsigned long long vtable, m_archive, m_name, m_fileSize, m_dataSize, m_offset, m_entryIndex, m_childCount, m_childList0, m_childList1, m_childList2; unsigned int m_flags, m_entryType; } ThisStruct;" + chr(10) + chr(10)')
a('    code = struct_def + code')
a('    return code')
a('')
a('LIFT_SYSTEM = (')
a('    "You are an expert C programmer specializing in reverse engineering. "')
a('    "Given Hex-Rays pseudocode from a stripped binary, produce clean, "')
a('    "compilable C code. The output must be a complete function with:\\\\n"')
a('    "- Use GCC-compatible types: long long instead of __int64\\\\n"')
a('    "- Correct return type\\\\n"')
a('    "- No placeholders or TODOs\\\\n"')
a('    "- No external function calls (implement inline if needed)\\\\n"')
a('    "- Just the function, no headers or main\\\\n\\\\n"')
a('    "IMPORTANT: The code must compile with g++ -O2 -std=c++11 -nostdlib -shared."')
a(')')
a('')
a('LIFT_PROMPT_TEMPLATE = (')
a('    "Convert this pseudocode to compilable C.\\\\n\\\\n"')
a('    "Callee prototypes (use these exact signatures when calling):\\\\n"')
a('    "{callee_prototypes}\\\\n\\\\n"')
a('    "{struct_context}\\\\n"')
a('    "```c\\\\n{pseudocode}\\\\n```\\\\n\\\\n"')
a('    "Return ONLY the C code (struct definition + function), nothing else."')
a(')')
a('')
a('async def _query_model(http, ollama_url, system, user_msg, *, ollama_model=""):')
a('    prompt = (')
a('        "' + LT + 'im' + GT + 'system' + LT + '/im' + GT + NL + system + LT + '/im' + GT + NL')
a('        + "' + LT + 'im' + GT + 'user' + LT + '/im' + GT + NL + user_msg + LT + '/im' + GT + NL')
a('        + "' + LT + 'im' + GT + 'assistant' + LT + '/im' + GT + NL')
a('    )')
a('    if ollama_model:')
a('        url = ollama_url.rstrip("/") + "/api/generate"')
a('        payload = {"model": ollama_model, "prompt": prompt, "stream": False, "think": False,')
a('                   "options": {"temperature": 0.3, "num_predict": 1024}}')
a('        resp = await http.post(url, json=payload)')
a('        resp.raise_for_status()')
a('        return resp.json().get("response", "").strip()')
a('    else:')
a('        payload = {"prompt": prompt, "temperature": 0.3, "n_predict": 1024}')
a('        resp = await http.post(ollama_url, json=payload)')
a('        resp.raise_for_status()')
a('        return resp.json().get("content", "").strip()')
a('')
a('def _extract_c_code(text: str) -> str:')
a('    text = re.sub(r\'```c?\\s*\\n?\', \'\', text)')
a('    text = re.sub(r\'```\\s*$', \'\', text, flags=re.MULTILINE)')
a('    text = text.strip()')
a('    lines = text.split(NL)')
a('    start = 0')
a('    for i, line in enumerate(lines):')
a('        if re.match(r\'^\\s*(typedef|struct|static|void|int|long|char|unsigned|float|double|__int|const|inline)\', line):')
a('            start = i')
a('            break')
a('    return NL.join(lines[start:]).strip()')
a('')
a('async def lift_function(pseudocode, original_bytes, func_name="", *, http=None, ollama_url="", ollama_model="", max_attempts=3, args=None):')
a('    import httpx as _httpx')
a('    if http is None:')
a('        http = _httpx.AsyncClient(timeout=120)')
a('        own_client = True')
a('    else:')
a('        own_client = False')
a('    result = LiftResult(func_name=func_name)')
a('    try:')
a('        for attempt_num in range(1, max_attempts + 1):')
a('            attempt = LiftAttempt(attempt_num=attempt_num)')
a('            struct_ctx = _extract_struct_context(pseudocode)')
a('            callees = set()')
a('            for m in re.finditer(r\'([A-Z]\\w*(?:::[A-Z]\\w*)*)\\s*\\(\', pseudocode):')
a('                callees.add(m.group(1))')
a('            callee_protos = []')
a('            for c in sorted(callees):')
a('                callee_protos.append(f"long long {c.replace(chr(58)+chr(58), chr(95))}(long long* args);")')
a('            callee_protos_str = NL.join(callee_protos)')
a('            user_msg = LIFT_PROMPT_TEMPLATE.format(callee_prototypes=callee_protos_str, struct_context=struct_ctx, pseudocode=pseudocode)')
a('            try:')
a('                raw_response = await _query_model(http, ollama_url, LIFT_SYSTEM, user_msg, ollama_model=ollama_model)')
a('                c_code = _normalize_types(_extract_c_code(raw_response))')
a('                attempt.c_code = c_code')
a('            except Exception as e:')
a('                attempt.compile_error = f"model query failed: {e}"')
a('                result.attempts.append(attempt)')
a('                continue')
a('            if not c_code:')
a('                attempt.compile_error = "model returned empty C code"')
a('                result.attempts.append(attempt)')
a('                continue')
a('            import tempfile as _tf')
a('            fd, _dll = _tf.mkstemp(suffix=".dll"); os.close(fd)')
a('            compile_result = compile_c_to_shared(c_code, _dll)')
a('            if not compile_result["ok"]:')
a('                attempt.compile_error = compile_result["error"][:300]')
a('                result.attempts.append(attempt)')
a('                continue')
a('            attempt.compiled = True')
a('            extract_result = extract_function_bytes(_dll, func_name)')
a('            if not extract_result["ok"]:')
a('                attempt.oracle_error = f"extract failed: {extract_result[\'error\']}"')
a('                result.attempts.append(attempt)')
a('                continue')
a('            recompiled_bytes = bytes.fromhex(extract_result["bytes"])')
a('            orig_result = emulate_function(original_bytes, args=args or [0,0,0,0])')
a('            recomp_result = emulate_function(recompiled_bytes, args=args or [0,0,0,0])')
a('            verdict = compare_emulations(orig_result, recomp_result)')
a('            attempt.verdict = verdict')
a('            if verdict.equivalent:')
a('                attempt.verified = True')
a('                result.verified_c = c_code')
a('                result.final_verdict = verdict')
a('                result.success = True')
a('                result.attempts.append(attempt)')
a('                break')
a('            else:')
a('                result.attempts.append(attempt)')
a('                previous_c = c_code')
a('    finally:')
a('        if own_client:')
a('            await http.aclose()')
a('    result.total_attempts = len(result.attempts)')
a('    return result')

p = pathlib.Path(r"C:\Users\Administrator\Desktop\scrape\mini-mythos\spectrIDA\spectrida\verify\lift.py")
p.write_text('\n'.join(lines), encoding='utf-8')
print(f"Wrote {len(lines)} lines")

import ast
ast.parse('\n'.join(lines))
print("Syntax OK")
